spring:
  jpa:
    database-platform: org.hibernate.spatial.dialect.mariadb.MariaDB103SpatialDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://darecaga.cafe24.com:3306/darecaga?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: darecaga
    password: aresteam!
    jwt:
      secret: aresteam!
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  config: classpath:logback-spring.xml
  org:
    hibernate:
      type:
        descriptor:
          sql: trace
  level:
    root: info

server:
  port: 8081


weather:
  apiURL: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst
  authKey: opn6jQE3EkqPya9gBAzCbJPxo4Cs%2BmM97zX%2Bwa9kyfsd4S46mqyyTt%2BYvIyVKDubvKubY9e6pG92wc%2FBX8BsuA%3D%3D
  posx: 127
  poxy: 37
